#!/usr/bin/env bash
# List all available backups file
set -o errexit
set -o nounset
set -o pipefail

# Get the directory of the current script
working_dir="$(dirname ${0})"

# Source the constants and messages scripts
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

# Display a welcome message
message_welcome "These are the backups you have got:"

# List the backup files in the backup directory
ls -lht "${BACKUP_DIR_PATH}"