#!/usr/bin/env bash
# Restore db from a specified backup file
set -o errexit
set -o nounset
set -o pipefail

# Determine the working directory

working_dir="$(dirname ${0})"


# Load required constants and functions
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"
# source "${working_dir}/_sourced/env.sh"
if [[ -z ${1+x} ]]; then
  message_error "Backup filename is not specified yet it is a required parameter. Make sure you provide one and try again."
  exit 1
fi

backup_filename="${BACKUP_DIR_PATH}/${1}"

if [[ ! -f "${backup_filename}" ]]; then
  message_error "No backup with the specified backup filename was found. Check out the 'backups' maintenance script output to see if there in one and try again"
  exit 1
fi

# Start the restoration process
message_welcome "Restoring the '${POSTGRES_DB}' database from the '${backup_filename}' backup..."

if [[ "${POSTGRES_USER}" == "postgres" ]]; then
  message_error "Restoring as 'postgres' user is not allowed. Assign 'POSTGRES_USER' env with another one and try again."
  exit 1
fi

# Set Postgres connection environment variables
export PGHOST="${POSTGRES_HOST}"
export PGPORT="${POSTGRES_PORT}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}"

# Drop the existing database
message_info "Dropping the database..."

# Drop the database
dropdb "${PGDATABASE}"

# Create a new database
message_info "Creating a new database..."

createdb --owner="${POSTGRES_USER}"
# Restore the database from the backup
message_info "Applying the backup to the new database..."
 
gunzip -c "${backup_filename}" | psql "${POSTGRES_DB}"
# Completion message
message_success "The '${POSTGRES_DB}' database has been restored successfully from the '${backup_filename}' backup"