# Generated by Django 4.1.7 on 2026-06-24 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+234 7048706557', max_length=30, null=True, region=None, verbose_name='Phone Number')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='About Me')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=20, verbose_name='Gender')),
                ('profile_picture', models.ImageField(blank=True, default='/profile_default.png', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('city', models.CharField(default='Lagos', max_length=255, verbose_name='City')),
                ('twitter_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='profiles.profile', verbose_name='Followers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
