upstream api {
    server api:8000; # api is the name of the service in docker-compose
}


server {
    client_max_body_size 20M; # increase max body size to 20MB for file uploads
    listen 80;
    
    # Root location - redirect to API docs
    location / {
        proxy_pass http://api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
    
    location /api/v1 {
        proxy_pass http://api; # pass requests to the api upstream
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header Host $host;
        proxy_redirect off;
       
    }
    
    location /swagger {
        proxy_pass http://api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
    
    location /supersecret {
        proxy_pass http://api; # pass requests to the api upstream
        
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header Host $host;
        proxy_redirect off;
       
    }

    location /redoc {
        proxy_pass http://api; # pass requests to the api upstream
        
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header Host $host;
        proxy_redirect off;
       
    }

    location /staticfiles/ {
        alias /app/staticfiles/; # serve static files directly from the container
       
    }

    location /mediafiles/ {
        alias /app/mediafiles/; # serve media files directly from the container
       
    }
}
