"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import environ 
env = environ.Env()
from datetime import timedelta



ROOT_DIR = Path(__file__).resolve().parent.parent  #2 folders up (config,settings)
PROJECT_DIR = ROOT_DIR.parent  # Project root (3 folders up - the actual /app directory)

APP_DIR = ROOT_DIR / "core_apps"
# django-extensions: allow runscript to find scripts in core_apps/scripts
RUNSCRIPT_SCRIPT_DIRS = [str(PROJECT_DIR / "core_apps" / "scripts")]


DEBUG = env.bool("DJANGO_DEBUG", default=False)

# Django Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites", # for django-allauth
    "django_extensions",
]


# Third-party apps
THIRD_PARTY_APPS = [
    #Add any third-party apps here
    "rest_framework",
    "django_filters",
    "corsheaders",
    "django_countries",
    "phonenumber_field",
    "drf_yasg",
    "djcelery_email",
    ## Auth
    "allauth",
    "rest_framework.authtoken",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",

    ]
#Core apps
LOCAL_APPS = [
    # Add your core apps here
    "core_apps.profiles",
    "core_apps.common",
    "core_apps.users",
]
#Combine all apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",# CORS Middleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {"default": env.db("DATABASE_URL")}



PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True

SITE_ID = 1  # for django-allauth

ADMIN_URL = "supersecret/" # for  admin to be accessed at /supersecret/ to notify admin of any security issues
#Usage http://localhost:8000/supersecret/ instead of http://localhost:8000/admin/ to access the admin panel

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/staticfiles/"
STATIC_ROOT = str(PROJECT_DIR / "staticfiles")


#Media config
MEDIA_URL = "/mediafiles/"
MEDIA_ROOT = str(PROJECT_DIR / "mediafiles")
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#Any  url with this will have cors headers added to it
CORS_URLS_REGEX = r"^api/.*$"  # Adjust this regex to match your allowed origins

# Custom user model
AUTH_USER_MODEL = "users.User"


#Celery Configuration

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
# Set timezone for Celery to match Django's timezone settings
if USE_TZ:
    CELERY_TIMEZONE = TIME_ZONE
else:
    CELERY_TIMEZONE = "UTC"

CELERY_RESULT_BACKEND_MAX_RETRIES =10
CELERY_TASK_SEND_SENT_EVENT = True


#Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(name)-12s %(asctime)s %(module)s "
                      "%(process)d %(thread)d %(message)s",
        }
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "root": {
        "level": "INFO",
        "handlers": ["console"]
    }
}

#=========RESTFRAMEWORK============
REST_FRAMEWORK ={
    "DEFAULT_AUTHENTICATION_CLASSES": ["rest_framework_simplejwt.authentication.JWTAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],

}

#==========SIMPLE JWT CONFIGURATION=============
SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "SIGNING_KEY": env("SIGNING_KEY"),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

#==========REST AUTH CONFIGURATION=============
REST_AUTH  = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "medium_api_clone_token",  # Name of the cookie to store the JWT
}

REST_AUTH_REGISTER_SERIALIZERS = {
    "REGISTER_SERIALIZER": "core_apps.users.serializers.CustomRegisterSerializer",  # Custom serializer for registration
}

#==========AUTHENTICATION BACKENDS CONFIGURATION=============   
AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",  # for django-allauth
    "django.contrib.auth.backends.ModelBackend",  # default
]

#==========ALLAUTH CONFIGURATION=============
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Use email for authentication
ACCOUNT_EMAIL_REQUIRED = True  # Require email for registration
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Require email verification for registration other options(none,optional,mandatory)
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # Allow browser-based confirmation links to verify immediately
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # Number of days before email confirmation expires  
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # Disable username field
ACCOUNT_USERNAME_REQUIRED = False  # Disable username field
